### ISSUE TITLE
 received events from 1 missing index

### ISSUE THREAD

**Issue by l08uk0** [b4b857f6ee/Selks#1]
Hi there
I hope some one can help me with the following error in Splunk
Received event for unconfigured/disabled/deleted index=$indexname$ with source="source::/var/log/suricata/eve.json" host="host::$hostname$" sourcetype="sourcetype::suricata". So far received events from 1 missing index(es).

I have crated the index = ids as advised in the installation
screenshot attached

Any hep will be much appreciated

![index](https://user-images.githubusercontent.com/72070749/97464144-d2ca3280-1940-11eb-997b-1764f965d228.png)
 process

**Comment by b4b857f6ee** [comment]
Hello,

The index name is ids :) .
And if you want the official version i already commit on the StamusNetwork App, she was release some week a go.
https://github.com/StamusNetworks/stamus_for_splunk

**Comment by l08uk0** [comment]
Hi,
Thanks for you answer
I configured the index name as "ids" as you can see in the screenshot above
but I still get the same error, what am I doing wrong
Thanks for your support

**Comment by b4b857f6ee** [comment]
Can you screen me the error please :).
You are on Splunk v7 or v8?

**Comment by l08uk0** [comment]
I am running version 7.3.1
the messages I get is : Received event for unconfigured/disabled/deleted index=$indexname$ with source="source::/var/log/suricata/eve.json" host="host::$hostname$" sourcetype="sourcetype::suricata". So far received events from 1 missing index(es).
![imagen](https://user-images.githubusercontent.com/72070749/97792058-79c8fb80-1bd9-11eb-934a-75a319c9a86a.png)

**Comment by b4b857f6ee** [comment]
How did you send your eve.json into the Splunk?
About the index, i guess you have delete the older and create a new?
did you install the suricata Add-On too?

**Comment by l08uk0** [comment]
Hi
Thanks for your reply
yes I have installed suricata add on 
![image](https://user-images.githubusercontent.com/72070749/97981696-f8d55400-1dd2-11eb-920b-0ad53853b7c3.png)
And also configured the UF to send the logs /var/log/suricata/eve.json
![image](https://user-images.githubusercontent.com/72070749/97982264-cf68f800-1dd3-11eb-86ae-2f19304dabc6.png)

I have configured the index = ids 2 times but not luck
I am running Splunk version 7.3.1 , maybe i upgrade to 8 is this supported on Splunk 8

**Comment by b4b857f6ee** [comment]
I was on 7.3.5 when testing. I'm now on v8 and it's working too.

inputs.conf
----------------------------------------
This is my input : 
[monitor:///var/log/suricata/eve.json]
disabled = false
index = ids
sourcetype = suricata
------------------------------------------

**Comment by l08uk0** [comment]
Thanks dude
The input.conf was the trick, I was configuring the index in splunk rather than in the UF.
It works now

**Comment by b4b857f6ee** [comment]
@l08uk0 Great

But be sure to check the official APP from Stamus :)

https://github.com/StamusNetworks/stamus_for_splunk

If it's ok for you, you can close the issue :)

**Comment by l08uk0** [comment]
sure thanks
